#! /bin/sh

bspc config border_width   0
bspc config window_gap     15
bspc config top_padding    35
bspc config right_padding  10
bspc config bottom_padding 10
bspc config left_padding   10
bspc config split_ratio    0.50

bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_by_distance     true
bspc config focus_follows_pointer true

bspc config normal_border_color  "#332d29"
bspc config active_border_color  "#817267"
bspc config focused_border_color "#504339"
bspc config presel_border_color  "#9a875f"
bspc config urgent_border_color  "#9f7155"
bspc config focused_locked_border_color "#9a875f"

bspc monitor -d main www term chat code misc

bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a feh floating=on

# autostart
feh --bg-scale ~/media/wallpapers/current.jpg
panel &
