#! /bin/sh

bspc monitor -d o o o o o o

desktop_config() {
	bspc config $1 $2
	for M in $(bspc query -M); do
		bspc config -m $M $1 $2
	done
}

desktop_config border_width		0	
desktop_config window_gap			40

bspc config window_gap			15
bspc config top_padding			35
bspc config right_padding		10
bspc config bottom_padding	10
bspc config left_padding		10
bspc config split_ratio			0.50

bspc config borderless_monocle		true
bspc config gapless_monocle				true
bspc config focus_by_distance			true
bspc config focus_follows_pointer	true

bspc config normal_border_color		"#f3f3f3"
bspc config active_border_color		"#f3f3f3"
bspc config focused_border_color	"#f3f3f3"
bspc config presel_border_color		"#f3f3f3"
bspc config urgent_border_color		"#f3f3f3"
bspc config focused_locked_border_color	"#f3f3f3"

bspc rule -a urxvt floating=off
bspc rule -a Chromium desktop=^2
bspc rule -a feh floating=on

# autostart
feh --bg-scale ~/media/wallpapers/current.jpg
panel &
