#!/bin/sh

source $XDG_CONFIG_HOME/panel/config
source $XDG_CONFIG_HOME/panel/colors

panel_workspaces() {
	ws=""
	IFS=':' read -a array <<< $(bspc control --get-status)
	for item in "${array[@]}"
	do
		name=${item#?}
		case $item in
			O*) # focused occupied
				ws="${ws}%{B#cc000000}%{F#ffc3c3c3} ${name} %{F-}%{B-}"
			;;
			F*) # focused free
				ws="${ws}%{B#cc000000}%{F#ffc3c3c3} ${name} %{F-}%{B-}"
			;;
			U*) # focused urgent
				ws="${ws}%{B#cc000000}%{F#ffff4500} ${name} %{F-}%{B-}"
			;;
			o*) # occupied
				ws="${ws}%{B#cc222222}%{F#ffc3c3c3} ${name} %{F-}%{B-}"
			;;
			f*) # free
				ws="${ws}%{F#ffc3c3c3} ${name} %{F-}"
			;;
			u*) # urgent
				ws="${ws}%{F#ffff4500} ${name} %{F-}"
			;;
		esac
		shift
	done
	echo "${ws}"
}

panel_title() {
	echo $(xtitle)
}

panel_battery() {
	echo "%{B#cc222222}%{F#ffc3c3c3} $(battery -f '%d')% %{F-}%{B-}"
}

panel_hostname() {
	echo "%{B#cc111111}%{F#ffc3c3c3} $(hostname) %{F-}%{B-}"
}

panel_clock() {
	echo "%{B#cc000000}%{F#ffc3c3c3} $(date +'%a %-I:%M %p') %{F-}%{B-}"
}

# print to panel

while [ "$(pidof xinit)" != "" ]; do
	echo "%{l}$(panel_workspaces)" \
			 "%{c}$(panel_title)" \
			 "%{r}$(panel_battery)$(panel_hostname)$(panel_clock)"
	sleep 0.1s
done
